#!/usr/bin/python
#-*- encoding: utf-8 -*-

# This file is part of the Pameng, 
# Pameng website: http://www.cnpameng.com/,
# Sina weibo: http://weibo.com/cnpameng.
#
# This file is part of WeiboMsgBackup.
#
# Copyright (C) 2013 Pameng.
# Pameng <pameng.cn@gmail.com>, 2013.
#
# WeiboMsgBackup is free software; you can redistribute it and/or modify 
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.
#
# WeiboMsgBackup is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WeiboMsgBackup; see the file COPYING3.  If not see
# <http://www.gnu.org/licenses/>.

#----------------------------------------------------------------------
# This file was generated by img2py.py
#----------------------------------------------------------------------

from wx.lib.embeddedimage import PyEmbeddedImage

AppIcon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAx1J"
    "REFUWIXV1l9olXUcx/HX+bNNZ2uujSKLSIsgu5C21C0D50UTzaKIIrarYRrihWiymZuTymGF"
    "0BqZmYMJXUTNEVnBTKhR6WYEEYRiZQs1sqalq7O5dnaeLs6ZrTGps4Rz+tw9z+/z/f4+z/v3"
    "feBHmio5ML+25MD82nTrLqfwlWo0VUX/rfGdwhUdsPpI0wPJNwvar0SAjBMI/ZNh/bd3dMFL"
    "L++5FyoXL/wSmnvP74WK54tb/0uAjBO4/AyEQiF47szVb8Gu/MRS+PChSCksbewNoPb8w/Og"
    "fWbnyqkEyDiBy87Aayc3z4X3+jt3wNHPu+fCTyf7boK+rnnXwc3Lj/0MpVc1LoGP67u60wmQ"
    "vQTueXbdjfDFcM0piDUvDEPB5sMJCBJJX1X4RC70TLs9Bj9uKctNJ0D2EhhTYUNPALF4MmvR"
    "wTV5MHjfK8MgPpxc3754Sh+T/QR2l+15BuqW37kFEkE8gN+2lYchd9OhAGbf8uatcHxV64l0"
    "AmQ/gTFd8+I3Z2G0/2wxBKnfYGD7ohB0nzs3AyqLi2PpBPj/EBjTonen98LR3oMLIe/aOX1w"
    "Zt2sOVMJkHEC0cdqXmiDfR37VkJiNAnl+lklQ/DEqoYiaGq6exgO3T9UDq/edexpqK8KN03W"
    "eMOGDRHYv7/vV/ju+x8KIBrJA2WlC/aTBQQuzUBFRWkuHPksZxhycyIgSGWsqCjthe6PWivG"
    "N2jOeXwXNIy0rYHKJZvehp7DvQ9CEBoBo4kAvL43MgOqqz8ZJJsITFQkuiCASE7q0pRIWqNR"
    "QzAYO5Q/3j+zqHIAYrF4AYTCoyA+kiof7Zl0r8wTWLt2RyHs3LnxwmSGWTdU/QL9Z38vgkgo"
    "mXlkNJ5yJJ8jyZERpKBOzwsNw8CFT6dN1vf06VMz/6rOoC6dy9atb9TAsmWzO6G8vPzieGNr"
    "a91t8GTd4eMQnnCiQWrK97YfXArV1fkfjF9vaWmJwvr1bfUQBF81k00EJqqj4+vd8Mij1ash"
    "Z1oOCJLDLf7HwN9ahKMFIBJNkhi5mLwwNT618X3Ytr1mxWT7ZJzAnwEw6+o3WZ9wAAAAAElF"
    "TkSuQmCC")

