#!/usr/bin/python
#-*- encoding: utf-8 -*-

# This file is part of the Pameng, 
# Pameng website: http://www.cnpameng.com/,
# Sina weibo: http://weibo.com/cnpameng.
#
# This file is part of WeiboMsgBackup.
#
# Copyright (C) 2013 Pameng.
# Pameng <pameng.cn@gmail.com>, 2013.
#
# WeiboMsgBackup is free software; you can redistribute it and/or modify 
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.
#
# WeiboMsgBackup is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WeiboMsgBackup; see the file COPYING3.  If not see
# <http://www.gnu.org/licenses/>.

#----------------------------------------------------------------------
# This file was generated by img2py.py
#----------------------------------------------------------------------

from wx.lib.embeddedimage import PyEmbeddedImage

StartImg = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAAZEUlEQVR4nO2da3CcZ3XHf1k2"
    "ykYRiqwoQlGEojiO47iJCTfXDQZCSMOdQKG0QGkoLVCaD3TaoZ1+6idmSju0pTP0QrkVSgnT"
    "0ilpCwVSE4IJIY0TJ9jGOI6iyLIibxRZkRV5o8jrfviff85Kka2Ldy279ZnZ0erd9/I8537O"
    "c87zwhk4A/+f4ayVHsAioQVoju/NQB/QBjQBJWAcmARmgBGgHMdOeTiVCFAEWoGu+KyJvy+M"
    "38cQsnuA++P/yxDim4BpRKjeODYVx/YDe4FBYBgYRYQ6JeBUIcBLgGuASxCSHwWq8X0HMIGQ"
    "WkTIqyJJKMZvE0AHkophRMh2RJA+4AXAQUSoEaCfJMqKwkoSoBkh/TrgSuBnwJ1ABamQEkLi"
    "EOLazYirH0RS0BnHh5C0tMT3MUSga5AaKsS9yvHc1wM/F+fsj2feF/c+6XCyCdAKbASuRapl"
    "CngC2IIQsgdx+EaE3B3A6vjcHfe4FnHuDkSgnrimjJDfEcf74zrivh1IpQ0hoqxH6qobuBj4"
    "KbA1zq3Uf+rzw8kiQBFYC7wZTX4XUinTiCijwADi6haE4Kb4XkUInolj1u+T8Xt3XDuJEGxu"
    "74rzynFdF0moLkSkCaSS2oBfBy4EHgG+Gfes1h0Tc+B5jX4Amtz7gY8gvftFxG0XxWcQTfZi"
    "hNCnEGKeRKrlCaTXexHyRhBiVyHd/nD834XU2mNxXyMf4FLgEHAASUU1xnIIEWwVsA0xQi9i"
    "lA4kRU/XExlzoVESUEActg64GSHjG4jz+0iuH0Lc2RnXTCIEd8Sx++LcbqQarKe74vgg4uou"
    "JGXDcW4l7tOMEDoSx/qQmirXjLE9/m9DhBlD6ula4HLgkzRQGholAS8G3ou4+knEXVuBI2ii"
    "z0cGciSOnY+QMITUQAlxX0v8tg8RB0SY8xHyp+MZR+NeRn45ntGJJOhInHcwfisi6TkXScEq"
    "UrV1xvOsml4Z1x2I59QVGiEBm4BfQUivIKSaqwsIacNowp1okrvjeEd8BhDyrQZsFO1qGvk9"
    "8Xcs7jWDJKsJcf5wPLMnvk8g5Pu6CpKA0Zr7jyA11QlsR7brHcB/ArfXA0G1UE8CtAE3AD8P"
    "fBpNoBu5jVOk6tmOuNDIH0KIsFrZS7qZk3FsDULKxQihNsztZARs4lYQV99BBmf3kAFbLxkl"
    "tyNitsZ5o8BVcb/7kArriHPfh+zLPyFC1gXqRYBu4F0ICXcgZE/H925y0v0IEW1o0sOkAW1F"
    "3LkR+ekFhIhpJP6OYqfivGr8VkWIJc5vjef1IlVVRGpwMJ6/gwzihkn7M424fRzZqo44z1LU"
    "C7wtfr+VOqU66kGAXuAWpHLuRgicRpzfgpBTQAgYRRNuRWpmOq5/J/JUWpAKeCiut6qaYmnp"
    "gwJCXokkyEuAlwI7UfB1T4wFRMQNCPHDSAKrMZam+H807vdBZFP+JMZ/QnCiBFgD/Cri9AnE"
    "+WVSD7ejQe5GiOyO48Nx7g3AKxBSbkfqqZFBUBvwS0hNTiOm2YGItBURrjvGOhbj70DMU4gx"
    "TwDXI4b5FGk/lgUnQoBe4MMohbAVTa4LDdbEqCCuso4vIG5+PfDyuHYLItDJhDYkEa9FUvAN"
    "cg6TaPzdMd7hOG5mmorP7yA19I+cgE1YLgG6kdq5n/RwZoC7kOivRxzUT07GCbQPx7l/Txrg"
    "lYJ25O+/LsbxaYTwNQi5ZTR2R+Tm9i40r3fFeZ9d7gCWQ4AW4LcQp29BnNSGOL0JIXkyfp9C"
    "+rMduaevAL6OQv2VRPx88CEUv/wIuI303EpoPmU0d7vBU2iuv4uI8HmWMaflBGKbgAuQ7rwM"
    "BSlDwDkI0TMoan0apQQuQX70NPDnyPidMvn4GtgJHEbSABq/F3tG0dzOQUHaYaSe2pDbvBnh"
    "sp8lBmtLJUAn8gLMwRcgTngEIbqK9PlTyGe/AOWA7kE5oLElPu9kwgyax0+QmrwQeAC5wBch"
    "xO4jPZ8XIgLtQ9LxRpSXWpJ7uhQCtCG9vwWF7keRqziNvIpRpIYOI2K8BPgA8DfAvwPPLGVg"
    "KwRHEQLvQQm5lyM1/ThSO1XgPOSAHEbIP4qI14nSFj9gCVKwWAI0AW+I8++NY2eTeZQjiPpP"
    "I85/AXAj8M/A9xc7mFMIDiHmWocWi3aiYK4NzfcgIkoJzbcpznklMs77F/ugxRLgUuAmFIo/"
    "gTyffciDOCsePhmDqSLO3wp8FxHndIQJpIJehYLLClK3+xGBatefR+LYEyj1vg2p4QVhMQQo"
    "AL+BqN6POGAcuWJPIr15COnEoygL+lPga5y+yDdUkDq6mkyJPw8Fbg7QvNbs9ejzkOrawSLU"
    "7mII8CIUwn+dDEKuRB7BdkRpZxevQ4b3M5yans5yoIKk/QaEcKfIHyZX5doQHqaQBrgOScVj"
    "C928sMDvJWTdH4gH9SNqz6BcDgj5U8hNeznwVU49H/9EYQD4HPD7SO3sQojuRJIwhnDQixjx"
    "B8j1Li5044UkYCPi9i1xs3WI0tuRjrwo/h5AofmdwA+XMLGFoEADFkGWAV7weQZ4N1KtTj/s"
    "R0x5CUL+AEqxrEWp7Qc4zhyOJwEtyJX0A5xhnCIXMryqtRbpyLuWPrd5went96AsZdPxTz9p"
    "sAV5R66mqJBLpmPIBhj+DXg10hDHhONJwFqUE/mXuEkvMkhOtD2JdFwB+D3E/ffOd6MlQify"
    "JM6Ke78TMcL9rLxqO4zU71uRl3cJGu8uhA9zejtaEl2P5rDzWDc8HgHejPz6I/HgfmR4z0XU"
    "Honr3xIP+kvqs3D9UjSxryIJ+x6KOW5BHsZB6rgitQwYQqqlG+HkMFI9TyF8dCGjPIE0xmqk"
    "huatrjiWCmpCeZ5+sp7GBU1eqKgixL8BeUj18npKyMtYiyY2idIbX0YS+Yco/ijV6XlLhSqa"
    "79UIP/aMOpCmKCFctKEFqlUIT/PCsQiwNm44jdTKODLIU/HQKuKADUgatp/YnGZBFYnzFNKv"
    "60njdhtKa9wC/HGMcyVgF2LCd8XYxsl6o2ZyvAW0uveqY91oPhVUQLU8P0HcN4pUwBRCTAUh"
    "/xykC+9AhqlesAatCf8EcdMzaFLnksT/b2Qj3ouI9HiM72R5TNV45i8iFb0KGeDno8Lip5HN"
    "HEO2651IGg7PvdF8EtCG3MshlGpdG8cG4obdyCV19Le1XrMKqKKQvpUsSXS43xXnWDK/HGP4"
    "CJpk59ybNRD2Ig+xjVzbHkbM0hnjdcagiBjrOTCfBFyB0grfRZxYRtRuQkhpjge/DUnHnXWa"
    "kGENMnIPkUuAZaQSz0KTOh8Z5IfiN1c3vC/m9CiNj8SnkbNwBfDtGEdvPHd/jPtFKDF5AMVQ"
    "P557k7kSUECTryCDMkDW4Djk7kdIeh1aF6g3FFDoDxl1O9UxTi5/7iULbHcgNfg1ZDM+gQx1"
    "M42F3UgjgJhziCwqs6NwF8LT5THeWTA3VC4xuwqgGjdcQ066GxmcMpmOqCcU0WLIFFJ5vWQN"
    "kBfNRxDHuwvGHtMeJA2rkXd2DfCdGHcjwMUENyJEe7zdMbYd5AKOl2dnLUrNlYAWlEwbJEtE"
    "NsRN+hEFXUx7P40R8yJSLaMIgdPx3dVrrgF1rVBffB+PcwrIPnwjfv8Y8lZaGjDWSeTjl+K5"
    "1yPcjCFPycjvJJ2XWTCXAE4uuauEuNA1Mq1I5K9AUXEjYDrG4eroSoxpglR/Y2TBlNuXjODx"
    "GOswqjX6OOLKj6PEYmudx/tNVGxg99Np6Uocc/fONrIK71mYq4Jcqj1Acr4r3FwO7nqZRkWj"
    "xRh4E9nTZQ5bjfRsS3xqmzwq8d0Ne0bIDCol3IRSGhsQ89xNfdqS7Pm4DnY85tAWx8YRrtxw"
    "UqSmom6uBHQjv7YlLhxDblQnWcdZisk2igCu0R8lJzYaAx9C0uAxOBnmHNFMnOd5mSA9SB/f"
    "ioj2GpS/qoda8hqJ1fMEWUs6FM/rIfveZiUW5xKgGU3eRta+9yiJ8F7kljaqD9fRpFXLJPIo"
    "HBlPkEW7bQj51TheQgRw92Qb2cxne/F5pI7KqPnijczjnSxxvAMIbxVkkFcjh6CI8DdAMtSs"
    "FMpcFeQA4k5EtbVI747WnH9VDL5RfnaVrCMFTWo3Qp6lY5xE/gxJHPeQ2W6U4vwi4vb7yAqG"
    "/0CIeVl8bkfGezkFt48i1eZeZBN7mtnVf1aJz0JhzvdLmN2P65p6yNr6ixBBGtXAVoxnVGPg"
    "JWTI3AHfjBjDPQH2flzBNo042si3LXHNam88pxV5Kt9E3HozatRbjloqo+DQ3uJU3Mdq202K"
    "tlPPQi0BmuLEB5Gx6ogBDpEl3lY7tQsPjYCnya0IKmhSnaSqGEYTKSNJLSJkz8S4m8jOem9f"
    "MIVUg5s23NxdRRL/ibjOSb6FlmvnQpVscWoia6Y6kITZkZh139p/SmT+ejQG7fSqO1HMkY2G"
    "c0hX2KneEYTMEmmEu+OYOb2VlBx7Q5YKV2f7uLO9lqoZVOm8DfgoS5ME54NWx5iGyYyxOd9B"
    "2yy1P5fKDv2tS8eQbrNe7owHLZU7lgJFJAFe9rTb1hff3X/QSXa5uHrZ44dcOq2QXDkZ5/l8"
    "b2tQIdMcd5IqbbFgx2EP2bm/FhFkPI5P15w7a7IGd6KA9GUP2aIzGoMrk95Fo6BIej8Vsja/"
    "TLqV9q9HyYaK1vhbID2jGbI0foxMJo7Hp6fmvibozcAXyB5jg5luPttngtpLa0MMsxWpT6+n"
    "e0yzJmuYIVuCWklxtl4dRwR6hsaqIXNTC1mN5qiyKX4fIn3v8TjXE7OnUSBX85zKsGF2X9pI"
    "XGMbtxn4H7T4Pt+4jgUXoToh4h7jCPlua2ojjf8smOuGWjeWyURXJ3LXHAdYvzYSphFy+sj+"
    "4AmEqDLZ6OdAcYZ0SS0lHWQq2/tJOCq1ni7GMzajBODXUcC2VLDD4K7/CpnM7InfvbZxTBUE"
    "qnJYHyfegzjM4gvp9rXXPKDeYD3eR+7zUEWcNIIQaJXUjRDuD3Gegy+7nQ7enFzcg+KZNyHJ"
    "+iEqKlgutKDkpHHljv0NiFmGYsxWjc/CXALYyxlChKiQHFEke2Yd7jcqFrAb2Ubq9F1kTsoL"
    "MB6zOc7IHyGdBvvhzjENomj1xWjZ879IVbQccJC3F+WXepDbaYmzO+x1jGPaAMgozrnrYbLx"
    "zpm8UcSdjfKEpsk9f1oQp5eRV+G+szWkZzYR57kjfiDG76ShpcPFY1eiguIvkB36JwK2P1Nk"
    "0OceZ+NvlExgHlcChlHn4ABaYOhCVKztGBxFtTvONtYbCqgkZggFM0XS0wGtEYySaXL796vJ"
    "7vaNZAqgHeV7LkKE/BTP9XBOBHqQBI2i7k+7nU6neEORF6H60lkwlwATpJ9vPbuG3NmkmRT1"
    "NhqTkKui4qsBUm2MkcGUV8dsC6wa96AJl2quXY8Yago1i9xF/avrXsZzke0u+/4Yz0bSSM+C"
    "+QhwkJzwBhL5pXjIXjLfMlDnyUB6Cs6fuzRmLRnlGvn2Mu4j/XC7p9eixpJvkcuF9YYmVKC1"
    "EyF9d4yjiJDdjtR1O0rYPWf9Ya4et07dhCbjfXa8m+FQPOAwyhc1AuxKeusxyJSDUwY9cexV"
    "yEnoQcwC4rabkXT+Ecp6Nqo50JuKDCEJXE2uxjka3oGI9J35bjCXALbcroDw3jt267yhxp2o"
    "F2DB+vdlQAGtS4+jifWRW9EMkPkg1ySZUM2obPFyZGA/S2NrSAuICX+M1s9tbMeQWmomG9fd"
    "zjrvTebCOJrg9vh9E7ns5n0e7o3fGlEaWCCrkL0+7dy+o/PmGF8TqedvQmUpf0bj1qtroQXN"
    "f4DchmcMBXXl+H+GzKzOa3vm4+B70WQ2I2S7Os62wG7UNlScZZtQL7Dn5SW+USTeaxDim5F3"
    "1BnjXAN8BaUPTmb5eh/yrHaT26H1ofpVM/E6pCa/d6ybzFcZV0FVZ7+A8hveb+cAylJeiGog"
    "D6CdUgYQYeoFr0VNf4/H+I6g2lSvQRxBNT/Xx3P/CjHDye5JezsqofxXZPDbUUTtCpKLUVp9"
    "NaoynNdjPFYwdTvpShXJlZxO0v+fQrU3N1Hf7Kj9/tqI1rsZXoXKD2fQxhp/S32Jv1hoRrHQ"
    "HlSTWkYS6K3TnOizq37MSPtYDRoVRLkesnzDhbFef92HJOMt8ZB6VZ9dikR5W9z3MFJ1NyKx"
    "/gu0jNjIdenjQRFtZTCFcmePoOYMb93QijTHM2hTk29zHCY5XjrB7UbNSJdNk/n5YbLE4oeo"
    "TLteHtH2uHdvPPdjKIr8FjKwA3V6znJhHZrvbpSf2o58fldBe/HFfQ27jnez47UoHUX9rmej"
    "xmtHxwNIt12MqP8Q4s5mjtMLtQQ4iLh+EzKw24AvoW1k6lFIdSLQilTgk8jFfBThydV6tU7K"
    "e9CYH37ubRYHBWRkP4R077XkruRryUWZUvz+OZQLaeRy5UrDDWjxvhfhYSPycmrLHUtx3qdZ"
    "hFY4HrKqSP9fQeYx2pGoufbR+yWMoMWMN5EbZv9fg2bkoX0PIda9AP1kwNeKVNSrke5f0EYt"
    "xK2DKGf+ejLvPYg8k2ZkLL1BXz9alPjgoqd0+kAJaYKnyOIt7wxWu+lrbxw/xCI7hxbqlD+K"
    "jMg7UB/UTuSZrCJtQAtZEfAwsgfdce7pvlkHCPnvQXbvr1H64QIUbR+Ic3pQbLQf2Yjvo275"
    "BWExm3UcQRTdhNyuc+O6QUSIJmR8zkbtOA+gIKVKNtWdzvBW5IXdipjtCYT48+L3ixGOhlGA"
    "WESdnItykRe7X1AZ9Y1dHQ/qR/ruPIT8GZQEG0eEKZKR4qOLfMapCG9DzsdtSL3sQ/N1BfQL"
    "yd3Yr0VtW58iF48WhMUSYAZx/ytR2UZ7XPtQ/F2DuMLlfzuQ7biFbC89HbYsM7SgrprXoMBv"
    "Gs31fDTfZpQHGkDpmavRhuX/gNTyomEpe8YdQpR/fzxkF7kOewj57n5ZzhjK5dyP9OcFSCee"
    "DkRoQQa3G2240YPm8hjibG/W9whirlXILkyiFM6S5rjUXRMfQ8m4tWQOvIICk0vI93e5YfpQ"
    "DOg1KEf+I07tjZw60T6gTyIJLiCJP5vcOv8QWaRwDpL6X0M9y0tea14qAY4iUbwSeTv3x2B7"
    "EEdMksh3f9Qu5BWsR3vtPI5sw6lEiAJaYPoo0vO3oXmVkbo9RO6N5EKvw/H/b6MNmpa1BrGc"
    "jVufQYm3dWQnjRuTDV7CfJzMonrD1l9G8UNtC+dKQifaGeYGlNHsRypzAAWYq1CC0JUOLyDL"
    "NN+N1NFXWKbLvdxXmLhQanMMcHvNABygeSfBS5FNOIiItxOpsJvIfXZWApoQAj+AiPA5cleA"
    "oTjWhzh9D8JVba/cbyIm+yKa27LgRN4h8zTi4uuQXdiNiNGLJKSKkD+MCNGHJrOb3Kn8D+J8"
    "p3OnadyGG+5cvBql0D+AjOjfoXWNF8f47Fafh7h7EAVZzyd7pd8fc/5TVnD7ekMfSj88gCTB"
    "+wp1Ic53zUyV2XUxvSiZ1YuCmamae7gAtx5BXDNKFl6DGKIN2aut5FYDriuaId9FNkgWpblZ"
    "vBcVeV1InQq86vUKkx7k8z+Mtjhzwm4SEchleja83eTeCgVUUtKDtkB2Me0Q8kB2kS/tWQgK"
    "yI3sis81aMORLrRuYdV5L1lq6W4byM5LF/a60qES329EEvAl6vQeynq+xKcVifUqlIodI18F"
    "4sG6Z9cLF/7ffVzrEEKmUerjarIlaQwh5RCz+5Q7kHookk0W7i17mNkLJsNkmfsEskVlpDLd"
    "g7aL2UW+TTGuDSgG+CQnqHZqod6vsepAuZMuJN4PkkuVTeS+DiNkEOdWoT4yu1jb3+sS8z6S"
    "eN4T4kJkNN0IUUZ2aRght4tstbK6cN+ZPTPIeGYk7t1GNlZvRuu/+6jjy3sMjXiPWBMS/bcj"
    "XfsZZqeu3eLq5jVXkU3G9ybk3npjQEMfWfdZQtFnhdTNO8gNktzR4/bQfsQILh9pJYu8rPLK"
    "ca23R+hA+Z3XIjfzbhpQ9tLIl3k2owjxcrSkuQVNulYSymQj2wjZpTlMlhO6P9kd6cU4p3ZL"
    "gEGyU9J1+JPx3dsFWEW1kkWz3k7A5fjuNbgB2aMZtA5dN5UzFxr9NlWX77nW9EHynb8j5Fa/"
    "g/G7S72N/BK5WdMgiTR3vHSQxr6DbGEyIWqR383slT03etjzcVfOZuSe/git+zZ0i8yT9Trb"
    "FvK1VZehPUE9eZc9emnTyC8i42diuZ/LyHdRbG0zhnV4B7NfgbiatDXd5MYf7uUtoddbnYeq"
    "L6zOGg4r8UbttWi3wxa0vjoQ33eTk25BSLMvXiLtAuTWaVZB1uHdiJgDZLNeL1lkbDUzhoh0"
    "PXJTm9Eiyh2c5PTISr3S3Ib6Kma/tW4IEcI1oe6v6iH33LEhdgf9KPkyZ6/O1fYTu0XJpeP2"
    "gNzdfi9yVU8Kx8+FlXynPGR6wDt1rUPLf6PkroludrDq8Wrc3J5fyAKBEioX6UbJM8cajyLi"
    "7WX2y6FXDFaaAPNBM0pdd5FR7SqyNN1d5+7mAWUv3cBRJRv4foYCPjf6rXRh13PgVCTAscD9"
    "CUWyQaN2C7AZMofk4uEzcAbOwBk4A2fglIX/BbKRwyWuZdH+AAAAAElFTkSuQmCC")
